import os, sys, time

os.system("cls || clear")
os.system("color 0b")
os.system("title github.com/uazeh")
print("=================\nConvert JS/Py to Exe\ngithub.com/uazeh\nUaze Ganteng:V\n=================")
plh = input("[1] JS to Exe\n[2] Py to Exe\n#--> = ")
if plh == "1":
    os.system("npm install -g pkg")
    os.system("cls")
    os.system("color 0b")
    os.system("title JS to Exe")
    print("=================")
    print("Convert JS to Exe")
    print("github.com/uazeh")
    print("Uaze Ganteng:V")
    print("=================")
    namefile = input("Enter name file (Must 1 directory) : ")
    time.sleep(1)
    os.system("pkg " + namefile + ".js")
    time.sleep(1)
    os.system("color 0b")
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
elif plh == '2':
    os.system("pip install pyinstaller")
    os.system("cls")
    os.system("color 0b")
    os.system("title Py to Exe")
    print("=================")
    print("Convert Py to Exe")
    print("github.com/uazeh")
    print("Uaze Ganteng:V")
    print("=================")
    namefile1 = input("Enter name file (Must 1 directory) : ")
    time.sleep(1)
    os.system("pyinstaller -F " + namefile1 + ".py")
    time.sleep(1)
    os.system("color 0b")
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)
    print("File already converted...")
    time.sleep(5)